server:
  port: 17890
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 39.97.108.189:8848
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: user-router
#          uri: lb://user-center
#          predicates:
#            - TimeBetween=上午9:00,下午5:00